# fly.toml app configuration file generated for mycodings-fly-test on 2025-02-08T12:53:37+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'mycodings-fly-test'
primary_region = 'sjc'
kill_signal = 'SIGINT'
kill_timeout = '5s'

[experimental]
  cmd = ['start_with_migrations.sh']
  entrypoint = ['sh']
  auto_rollback = true

[build]

[env]
  DATABASE_URL = 'file:/data/sqlite.db'
  PORT = '8080'

[[mounts]]
  source = 'data'
  destination = '/data'

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[services.http_checks]]
  interval = '10s'          # 헬스 체크 간격 (10초마다 실행)
  timeout = '2s'            # 헬스 체크 요청의 타임아웃 (2초)
  grace_period = '5s'       # 인스턴스 시작 후 헬스 체크 시작 전 대기 시간 (5초)
  method = 'get'            # HTTP 메서드 (GET 요청 사용)
  path = '/healthcheck'     # 헬스 체크를 위한 엔드포인트 경로
  protocol = 'http'         # 프로토콜 (HTTP 사용)
  tls_skip_verify = false   # TLS 인증서 검증 여부 (false로 설정 시 인증서 검증)
  
[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
